import { CartContextProvider } from "@/context/Cart";
import "./globals.css";
import Layout from "@/components/Layout";

export const metadata = {
  title: `Next Store |`,
  description: "Next Store Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartContextProvider>
          <Layout>{children}</Layout>
        </CartContextProvider>
      </body>
    </html>
  );
}
